const fs = require("fs")
console.log("START")
setImmediate(()=>console.log("Immediate-1"))
setTimeout(()=>{console.log("Timer-1")},0)
fs.readFile("abc.txt",(err,data)=>{
    console.log("Reading-START")
    setImmediate(()=>console.log("Immediate-2"))
    setTimeout(()=>{console.log("Timer-2"),0})
    process.nextTick(()=>console.log("Tick-2"))
    Promise.resolve().then(()=>console.log("Promise-2"))
    console.log("Reading End")
})
Promise.resolve().then(()=>{console.log("Promise - 1")})
process.nextTick(()=>{console.log("Tick-1")})
console.log("END")
