# -*- coding: utf-8 -*-
"""gd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMIY9TvHQemf360givUaCdm0gxs5Mgw0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading data
df = pd.read_csv("/content/cgpa_package_linear_regression.csv")
df

df = df[df["package"].notnull()]
df.drop("student_id",axis=1,inplace=True)
df

x = df[["cgpa"]]
y = df["package"]
type(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

# handling missing  value
x_train["cgpa"] = x_train["cgpa"].fillna(x_train["cgpa"].mean())
x_test["cgpa"] = x_test["cgpa"].fillna(x_train["cgpa"].mean())

sns.scatterplot(x=x_train["cgpa"],y=y_train)
plt.show()

# w and b are the model parameter
# learing_rate and epochs are the hyperparameter
w = 0
b = 0
learning_rate = 0.0001
epochs = 100000
history = []
for i in range(epochs):
  x = x_train["cgpa"]
  y_pred = w*x + b

  error = y_train - y_pred

  cost = (error**2).sum()
  history.append(cost)
  # error = y - y_pred
  dw = -2 * (x*error).sum()
  db = -2 * error.sum()

  w = w - learning_rate * dw
  b = b - learning_rate * db

  final_w = w
  final_b = b

print(f"w : {final_w} b : {final_b}")
print(history[0:10])
print(history[-10:-1])

# plot the graph for cost function
plt.plot(range(100000),history,label="cost function",color="red")
plt.xlabel("epochs")
plt.ylabel("cost")
plt.legend()
plt.show()

y_pred = final_w * x_train["cgpa"] + final_b

sns.scatterplot(x=x_train["cgpa"],y=y_train)
plt.plot(x_train["cgpa"],y_pred,color="red")
plt.show()
#

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

lr

print(f"w : {lr.coef_} , b : {lr.intercept_}")

y_pred = lr.predict(x_train)
sns.scatterplot(x=x_train["cgpa"],y=y_train)
plt.plot(x_train["cgpa"],y_pred,color="red")
plt.show()
#