# -*- coding: utf-8 -*-
"""gd_polynomial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DlNWLzzFNF869s4xn0P9fLvdGg2GQtja
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.DataFrame({
    "Hours_Studied": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ],

    "Performance_Score": [
        11, 15, 20, 27, 35,
        44, 54, 65, 77, 90,
        104, 119, 135, 152, 170,
        189, 209, 230, 252, 275
    ]
})
df

# view relation between data point
sns.scatterplot(x=df["Hours_Studied"], y=df["Performance_Score"])
plt.show()

# Seperate X and y
X = df[["Hours_Studied"]]
Y = df["Performance_Score"]
X,Y

# train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

# Feature Engineering for polynomial regression
X_train["x2"] = X_train["Hours_Studied"]**2
X_test["x2"] = X_test["Hours_Studied"]**2

# y_pred = b + w1x1 + w2x2**2
# implement gradient descent
b = 0
w1 = 0
w2 = 0
learning_rate = 0.0000001
epochs = 20000
history = []
lambda_value = 10000
for i in range(epochs):
   x1 = X_train["Hours_Studied"]
   x2 = X_train["x2"]

   y_pred = b + w1 * x1 + w2 * x2
   error = y_pred - Y_train
   ridge_penalty = lambda_value * (w1**2 + w2**2)
   #error = error + ridge_penalty
   cost = np.mean(error**2) + ridge_penalty
   history.append(cost)

   db = (2/len(X_train)) * error.sum()
   dw1 = (2/len(X_train)) * (error * x1).sum() + 2 * lambda_value * w1
   dw2 = (2/len(X_train)) * (error * x2).sum() + 2 * lambda_value * w2

   b = b - learning_rate * db
   w1 = w1 - learning_rate * dw1
   w2 = w2 - learning_rate * dw2

print(f"b : {b}")
print(f"w1 : {w1}")
print(f"w2 : {w2}")

X_train_sorted = X_train.sort_values(by="Hours_Studied")
Y_train_sorted = Y_train.loc[X_train_sorted.index]
y_pred = b + w1 * X_train_sorted["Hours_Studied"] + w2 * X_train_sorted["x2"]
y_pred

# now plot data point and polynomial line
sns.scatterplot(x = X_train_sorted["Hours_Studied"],y = Y_train_sorted)
plt.plot(X_train_sorted["Hours_Studied"],y_pred,color="red")
plt.show()

# calculating r-2 score
from sklearn.metrics import r2_score
y_pred = b + w1 * X_test["Hours_Studied"] + w2 * X_test["x2"]
r2_score(Y_test,y_pred)