# -*- coding: utf-8 -*-
"""MLR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xu281IzhOHr9qcajp2KjE6HgnDyOdhNn
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/cgpa_package_multi_lr.csv")
df

# Data Quality Check
print(f"Shape : {df.shape}")
print(f"Datatypes : {df.dtypes}")
print(f"Descirbe : {df.describe()}")

df.describe()

df.isna().sum()

#Checking Multicolinearity
sns.pairplot(df)
plt.show()

# heatmap
sns.heatmap(df.corr(),annot=True)
plt.show()

# univarient analysis
print(f"Mean : {df["cgpa"].mean()}")
print(f"Median : {df["cgpa"].median()}")
print(f"Skew : {df["cgpa"].skew()}")

sns.histplot(df["cgpa"],kde=True,bins=20)
plt.show()

# Checking Outliers
Q1 = df["cgpa"].quantile(0.25)
Q3 = df["cgpa"].quantile(0.75)
IQR = Q3-Q1
lower_boundry = Q1-1.5*IQR
upper_boundry = Q3+1.5*IQR

df[(df["cgpa"] < lower_boundry) | (df["cgpa"]>upper_boundry)]

sns.boxplot(x = df["cgpa"])
plt.show()

sns.boxplot(x=df["project"])
plt.show()

# Remove row whose target column value in null
df = df[df["package"].notnull()]
df

# Seperate X and Y
x = df.iloc[:,[0,1,2,4]]
y = df["package"]
y

# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

# Handline missing value
x_train.isna().sum()
x_train["cgpa"] = x_train["cgpa"].fillna(x_train["cgpa"].mean())
x_test["cgpa"] = x_test["cgpa"].fillna(x_train["cgpa"].mean())

x_train["internship"] = x_train["internship"].fillna(1.0)
x_test["internship"] = x_test["internship"].fillna(1.0)


x_test

# Model Training is Done
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

lr

# Check the Model Parameter
print(f"Slope: {lr.coef_}")

print(f"Intercept : {lr.intercept_}")

# Prediction
x_test,y_test
lr.predict([[7.7,1.0,2,79]])

y_pred = lr.predict(x_test)
y_pred

from sklearn.metrics import mean_squared_error
error = mean_squared_error(y_test,y_pred)
print(error)