# -*- coding: utf-8 -*-
"""polynomial_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVicMWZAccqvHeMQ5RdD5X5KQwNyeghA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Data Set
df = pd.DataFrame({
    "Hours_Studied": [
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
        31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
        81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99, 100
    ],

    "Exam_Score": [
        12, 15, 18, 20, 23, 25, 28, 30, 33, 35,
        38, 40, 42, 45, 47, 49, 51, 54, 56, 58,
        60, 62, 64, 66, 68, 70, 72, 74, 76, 78,
        80, 82, 84, 86, 88, 89, 90, 91, 92, 93,
        94, 95, 96, 97, 98, 99, 100, 99, 98, 97,
        96, 95, 94, 93, 92, 91, 90, 89, 88, 87,
        86, 85, 84, 83, 82, 81, 80, 79, 78, 77,
        76, 75, 74, 73, 72, 71, 70, 69, 68, 67,
        66, 65, 64, 63, 62, 61, 60, 59, 58, 57,
        56, 55, 54, 53, 52, 51, 50, 49, 48, 47
    ]
})
df

# Data Quality Check
print(f"Shape : {df.shape}")
print(f"Datatypes : {df.dtypes}")
print(f"Descriptive  :{df.describe()}")
print(f"Null Values : {df.isnull().sum()}")

# Distribution
sns.histplot(df["Hours_Studied"],kde=True,bins=20)
plt.show()

print(f"Mean : {df['Hours_Studied'].mean()}")
print(f"Median : {df['Hours_Studied'].median()}")
print(f"Skew : {df['Hours_Studied'].skew()}")

# outlier
sns.boxplot(x = df["Hours_Studied"])
plt.show()

# Plot datapoints
sns.scatterplot(x=df["Hours_Studied"],y=df["Exam_Score"])
plt.show()

# Seperate X and Y
x = df[["Hours_Studied"]]
y = df["Exam_Score"]

# train_test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
x_train

# Train Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)
lr

print(f"Coefficient : {lr.coef_}")
print(f"Intercept : {lr.intercept_}")

sns.scatterplot(x=x_test["Hours_Studied"],y=y_test)
plt.plot(x_test,lr.predict(x_test),color="red")
plt.show()

# calculate R-2 score
from sklearn.metrics import r2_score
r2_score(y_test,lr.predict(x_test))

x_train
y_train
x_test
y_test

# Applying Polynomial Transformation
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
x_train_poly = poly.fit_transform(x_train)
x_test_poly = poly.transform(x_test)
x_test_poly

# Now applying LinearRegression on Transformed data
from sklearn.linear_model import LinearRegression
lr_poly = LinearRegression()
lr_poly.fit(x_train_poly,y_train)
lr_poly

#lr_poly.coef_
lr_poly.intercept_

# plot Actual Data points
x_test
x_test_sorted = x_test.sort_values(by="Hours_Studied")

sns.scatterplot(x=x_test_sorted["Hours_Studied"],y=y_test)
plt.plot(x_test_sorted["Hours_Studied"],lr_poly.predict(poly.transform(x_test_sorted)),color="red")
plt.show()

# Calculating R-2 Score
r2_score(y_test,lr_poly.predict(x_test_poly))