# -*- coding: utf-8 -*-
"""test_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukuT5HMusbMaToQRnpuMDhEnj8nNz8ik
"""

import numpy as np # Linear Algebra
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/content/cgpa_package_linear_regression.csv")
df

print(f"Shape : {df.shape}")
print(f"Datatypes : {df.dtypes}")
df.describe()

sns.boxplot(df["cgpa"])
plt.title("CGPA Distribution & Outliers")
plt.show()

print(f"Mean : {df["cgpa"].mean()}")
print(f"Std : {df["cgpa"].std()}")
print(f"Median : {df["cgpa"].median()}")
df["cgpa"] = df["cgpa"].fillna(df["cgpa"].mean())

df["cgpa"].skew()

sns.histplot(df["cgpa"],bins=10,kde=True)
plt.title("CGPA Distribution")
plt.show()

print(f"Mean : {df["package"].mean()}")
print(f"Median : {df["package"].median()}")
print(f"Skewed : {df["package"].skew()}")
df["package"] = df["package"].fillna(df["package"].mean())

sns.histplot(df["package"],kde=True, bins=10)
plt.show()

df
df.isna().sum()

sns.scatterplot(data=df,x="cgpa",y="package")
plt.plot()

df["cgpa"].corr(df["package"])

df
X = df[["cgpa"]]
Y = df[["package"]]
X

Y

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)
X_train

Y_train

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,Y_train) # Model Trained

print(f"Slope m : {model.coef_}")
print(f"Intercept c : {model.intercept_}")
print(X_test)
print(Y_test)

model.predict([[8.0]])

X_test
type(X_test)
Y_test

X_test
type(X_test)
Y_test
type(Y_test)
sns.scatterplot(x=X_test["cgpa"],y=Y_test["package"])
plt.plot(X_test,model.predict(X_test),color="red")
plt.show()