"""add skill and gender in employee

Revision ID: c5bb715fa9b3
Revises: 6119cfbef1bd
Create Date: 2026-06-09 11:27:36.676474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bb715fa9b3'
down_revision: Union[str, Sequence[str], None] = '6119cfbef1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('skill', sa.String(length=100), nullable=False))
    op.add_column('employee', sa.Column('gender', sa.String(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'gender')
    op.drop_column('employee', 'skill')
    # ### end Alembic commands ###
