"""removing age column

Revision ID: c5f321dcd828
Revises: c5bb715fa9b3
Create Date: 2026-06-09 11:30:16.272951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c5f321dcd828'
down_revision: Union[str, Sequence[str], None] = 'c5bb715fa9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
