"""creating foreigh key in profile

Revision ID: ab246d19145e
Revises: 75ad6c7f6192
Create Date: 2026-06-12 10:28:57.917140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab246d19145e'
down_revision: Union[str, Sequence[str], None] = '75ad6c7f6192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profile', ['student_id'])
    op.create_foreign_key(None, 'profile', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='foreignkey')
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'student_id')
    # ### end Alembic commands ###
