"""createing foreign key department id

Revision ID: c2b5e3b5ce68
Revises: 3a621aaf5a3b
Create Date: 2026-06-12 09:54:46.918144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2b5e3b5ce68'
down_revision: Union[str, Sequence[str], None] = '3a621aaf5a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'course', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'department_id')
    # ### end Alembic commands ###
